version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt/:/etc/letsencrypt/
      - ./nginx/html/:/var/www/
      - ./nginx/logs/:/var/log/nginx_log/
    ports:
        - 80:80
        - 443:443
    
    extra_hosts:
    - "host.docker.internal:host-gateway"

  bxx:
    image: bxx-python:latest
    container_name: bxx
    volumes:
      - ./python/bxx/:/python-docker

  ssrf:
    image: ssrf-python:latest
    container_name: ssrf
    volumes:
      - ./python/ssrf/:/python-docker

